### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by x64architecture** [nijel/enca#18]
Happens on boot on the latest version of Arch Linux:
enca 1.8.0
tracker 1.8.0-2 (gnome)

Note: This might be a bug in tracker not sure though as the coredump leads to enca.
[gnome bug 764924](https://bugzilla.gnome.org/show_bug.cgi?id=764924)

If you need more info please ask.

If you want the full coredump please provide a non-public way (email maybe) to do so as there is sensitive info in it.

dmesg:
`[   45.283917] tracker-extract[1115]: segfault at 7fc276755000 ip 00007fc2c700d8c0 sp 00007fff3c8b2788 error 4 in libenca.so.0.5.1[7fc2c6fff000+2d000]`

gdb bt:
```
[kurt@kc-x64architecture ~]$ sudo coredumpctl gdb 1115
           PID: 1115 (tracker-extract)
           UID: 1000 (kurt)
           GID: 1000 (kurt)
        Signal: 11 (SEGV)
     Timestamp: Mon 2016-04-11 20:04:16 EDT (20s ago)
  Command Line: /usr/lib/tracker/tracker-extract
    Executable: /usr/lib/tracker/tracker-extract
 Control Group: /user.slice/user-1000.slice/session-c4.scope
          Unit: session-c4.scope
         Slice: user-1000.slice
       Session: c4
     Owner UID: 1000 (kurt)
       Boot ID: 6838a9e3b5b8470d98437da96502a83c
    Machine ID: bf66ee7e00694ec481e9564ee82c651e
      Hostname: kc-x64architecture
      Coredump: /var/lib/systemd/coredump/core.tracker-extract.1000.6838a9e3b5b8470d98437da96502a83c.1115.1460419456000000000000.lz4
       Message: Process 1115 (tracker-extract) of user 1000 dumped core.
                
                Stack trace of thread 1115:
                #0  0x00007fc2c700d8c0 count_characters (libenca.so.0)
                #1  0x00007fc2c700dca1 make_guess (libenca.so.0)
                #2  0x00007fc2c700ea58 enca_analyse_const (libenca.so.0)
                #3  0x00007fc2c9abc1cd tracker_encoding_guess_enca (libtracker-extract.so.0)
                #4  0x00007fc2c9ab52e8 tracker_encoding_guess (libtracker-extract.so.0)
                #5  0x00007fc27674f9d8 get_encoding (libextract-mp3.so)
                #6  0x00007fc27674fafd convert_to_encoding (libextract-mp3.so)
                #7  0x00007fc27674f213 get_id3v24_tags (libextract-mp3.so)
                #8  0x00007fc276752a78 parse_id3v24 (libextract-mp3.so)
                #9  0x000000000040b10e get_file_metadata (tracker-extract)
                #10 0x000000000040b243 get_metadata (tracker-extract)
                #11 0x000000000040b480 dispatch_task_cb (tracker-extract)
                #12 0x00007fc2c8716dba g_main_context_dispatch (libglib-2.0.so.0)
                #13 0x00007fc2c8717160 n/a (libglib-2.0.so.0)
                #14 0x00007fc2c8717482 g_main_loop_run (libglib-2.0.so.0)
                #15 0x0000000000409b14 main (tracker-extract)
                #16 0x00007fc2c812f710 __libc_start_main (libc.so.6)
                #17 0x0000000000409ba9 _start (tracker-extract)
                
                Stack trace of thread 1291:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1292:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1118:
                #0  0x00007fc2c81edc3d poll (libc.so.6)
                #1  0x00007fc2c87170fc n/a (libglib-2.0.so.0)
                #2  0x00007fc2c871720c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fc2c01d943d n/a (libdconfsettings.so)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1309:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875bafa g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fc2c86eb929 n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e2e6 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1300:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875bafa g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fc2c86eb929 n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e2e6 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1311:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875bafa g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fc2c86eb929 n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e2e6 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1288:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1294:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1296:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1119:
                #0  0x00007fc2c81edc3d poll (libc.so.6)
                #1  0x00007fc2c87170fc n/a (libglib-2.0.so.0)
                #2  0x00007fc2c871720c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fc2c8717249 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1297:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1290:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1295:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1307:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875bafa g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fc2c86eb929 n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e2e6 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1289:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1293:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875b9df g_cond_wait (libglib-2.0.so.0)
                #2  0x00007fc2c86eb96b n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e365 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1310:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875bafa g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fc2c86eb929 n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e2e6 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1308:
                #0  0x00007fc2c81f27f9 syscall (libc.so.6)
                #1  0x00007fc2c875bafa g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fc2c86eb929 n/a (libglib-2.0.so.0)
                #3  0x00007fc2c873e2e6 n/a (libglib-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)
                
                Stack trace of thread 1120:
                #0  0x00007fc2c81edc3d poll (libc.so.6)
                #1  0x00007fc2c87170fc n/a (libglib-2.0.so.0)
                #2  0x00007fc2c8717482 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fc2c936c6d6 n/a (libgio-2.0.so.0)
                #4  0x00007fc2c873d975 n/a (libglib-2.0.so.0)
                #5  0x00007fc2c84b7424 start_thread (libpthread.so.0)
                #6  0x00007fc2c81f6cbd __clone (libc.so.6)

GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/tracker/tracker-extract...done.
[New LWP 1115]
[New LWP 1291]
[New LWP 1292]
[New LWP 1118]
[New LWP 1309]
[New LWP 1300]
[New LWP 1311]
[New LWP 1288]
[New LWP 1294]
[New LWP 1296]
[New LWP 1119]
[New LWP 1297]
[New LWP 1290]
[New LWP 1295]
[New LWP 1307]
[New LWP 1289]
[New LWP 1293]
[New LWP 1310]
[New LWP 1308]
[New LWP 1120]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/lib/tracker/tracker-extract'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  count_characters (analyser=analyser@entry=0x21b50e0) at guess.c:765
765	    counts[buffer[i]]++;
[Current thread is 1 (Thread 0x7fc2ca24c800 (LWP 1115))]
(gdb) bt
#0  count_characters (analyser=analyser@entry=0x21b50e0) at guess.c:765
#1  0x00007fc2c700dca1 in make_guess (analyser=0x21b50e0) at guess.c:247
#2  analyse (analyser=0x21b50e0, 
    buffer=0x7fc27624c3ac <error: Cannot access memory at address 0x7fc27624c3ac>, size=18446744073709551615) at guess.c:202
#3  0x00007fc2c700ea58 in enca_analyse_const (
    analyser=analyser@entry=0x21b50e0, 
    buffer=buffer@entry=0x7fc27624c3ac <error: Cannot access memory at address 0x7fc27624c3ac>, size=size@entry=18446744073709551615) at guess.c:166
#4  0x00007fc2c9abc1cd in tracker_encoding_guess_enca (
    buffer=buffer@entry=0x7fc27624c3ac <error: Cannot access memory at address 0x7fc27624c3ac>, size=size@entry=18446744073709551615)
    at tracker-encoding-enca.c:43
#5  0x00007fc2c9ab52e8 in tracker_encoding_guess (
    buffer=0x7fc27624c3ac <error: Cannot access memory at address 0x7fc27624c3ac>, size=18446744073709551615, confidence=confidence@entry=0x7fff3c8b28b0)
    at tracker-encoding.c:68
#6  0x00007fc27674f9d8 in get_encoding (data=<optimized out>, 
    size=<optimized out>, encoding_found=0x0) at tracker-extract-mp3.c:683
#7  0x00007fc27674fafd in convert_to_encoding (
    str=0x7fc27624c3ac <error: Cannot access memory at address 0x7fc27624c3ac>, len=-1, from_codeset=<optimized out>, error_out=0x0, bytes_written=0x0, 
    bytes_read=0x0, to_codeset=0x7fc276752baa "UTF-8")
---Type <return> to continue, or q <return> to quit---
    at tracker-extract-mp3.c:735
#8  0x00007fc27674f213 in get_id3v24_tags (frame=<optimized out>, 
    data=0x7fc27624c0af <error: Cannot access memory at address 0x7fc27624c0af>, csize=csize@entry=764, info=info@entry=0x7fff3c8b2ae8, 
    filedata=filedata@entry=0x7fff3c8b2a30, metadata=<optimized out>, 
    uri=<optimized out>) at tracker-extract-mp3.c:1296
#9  0x00007fc276752a78 in parse_id3v24 (uri=<optimized out>, 
    metadata=<optimized out>, offset_delta=<synthetic pointer>, 
    filedata=0x7fff3c8b2a30, info=0x7fff3c8b2ae8, size=5242880, 
    data=<optimized out>) at tracker-extract-mp3.c:1942
#10 parse_id3v2 (uri=<optimized out>, metadata=<optimized out>, 
    filedata=0x7fff3c8b2a30, info=0x7fff3c8b2ae8, size=5242880, 
    data=0x7fc27624c000 <error: Cannot access memory at address 0x7fc27624c000>) at tracker-extract-mp3.c:2262
#11 tracker_extract_get_metadata (info=0x7fc290001a80)
    at tracker-extract-mp3.c:2348
#12 0x000000000040b10e in get_file_metadata (task=task@entry=0x7fc2a80084c0, 
    info_out=info_out@entry=0x7fff3c8b2d90) at tracker-extract.c:332
#13 0x000000000040b243 in get_metadata (task=task@entry=0x7fc2a80084c0)
    at tracker-extract.c:532
#14 0x000000000040b480 in dispatch_task_cb (task=0x7fc2a80084c0)
    at tracker-extract.c:645
#15 0x00007fc2c8716dba in g_main_context_dispatch ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/libglib-2.0.so.0
#16 0x00007fc2c8717160 in ?? () from /usr/lib/libglib-2.0.so.0
#17 0x00007fc2c8717482 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#18 0x0000000000409b14 in main (argc=1, argv=0x7fff3c8b3068)
    at tracker-main.c:388
```

**Comment by x64architecture** [comment]
Downgrading libenca to 1.16 (The previous Arch Linux version) solves the problem, but it still could be related to tracker-extract.

**Comment by nijel** [comment]
Given that there are almost no code changes in the library between 1.16 and 1.18, I'd say it's more likely bug in tracker or compilation rather than issue enca.

The only source code change in the library between these two versions is 7ccfe9d8ad1d3f4eabc0a6fbfffc2c7c08169430 and I'm pretty sure it doesn't have any side effects...

**Comment by x64architecture** [comment]
Yea I saw that and I figured it was probably something else. It was actually just a coincidence that it worked. Now it always segfaults which probably means that their is a OOB read/write some where. I'll close this unless I find a way back to libenca. Thanks for the reply.
